name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/publish_docs.yml'

concurrency:
  group: "publish_docs"
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build_docs.yml

  publish:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Download built docs
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: ./built_docs

      - name: ls built_docs
        run: ls ./built_docs

      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: github.event_name == 'push'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./built_docs
        if: github.event_name == 'push'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: github.event_name == 'push'

